#!/bin/bash

# Build all components separately on the host computer.
# Use this script to build every artifact needed for a
# Docker deployment using the 'host build' configuration.


# Articles backend
cd coordinator-articles-backend
printf "\nBuilding articles-backend artifact: JAR file...\n"

./gradlew bootJar

if [ $? -ne 0 ]; then
    printf "\nFailed building articles-backend, exiting!\n"
    exit
fi
cd ..

# Auth backend
cd coordinator-auth-backend
printf "\nBuilding auth-backend artifact: JAR file...\n"

./gradlew bootJar

if [ $? -ne 0 ]; then
    printf "\nFailed building auth-backend, exiting!\n"
    exit
fi
cd ..

# Frontend
cd coordinator-frontend
printf "\nBuilding frontend artifact: NextJS standalone build...\n"

npm run build

if [ $? -ne 0 ]; then
    printf "\nFailed building frontend, exiting!\n"
    exit
fi
cd ..

printf "\nTasks finished, all artifacts built!\n"
