# Main configuration script for application deployment

services:
    # Common frontend
    common-frontend:
        container_name: common-frontend
        build:
            context: ./coordinator-frontend
        ports:
            - "3000:3000"
        networks:
            - internal

    # Common proxy, all requests not made to the frontend
    # are routed through this reverse proxy
    common-proxy:
        container_name: common-proxy
        build:
            context: ./coordinator-proxy
        ports:
            - "80:80"
        networks:
            - internal

    # Articles components
    articles-backend:
        container_name: articles-backend
        build:
            context: ./coordinator-articles-backend
            args:
                config: docker.properties
        ports:
            - "8080:8080"
        networks:
            - internal
    articles-db:
        container_name: articles-db
        image: mysql:8.0
        environment:
            MYSQL_DATABASE: "articles"
            MYSQL_ROOT_PASSWORD: ${ARTICLES_DB_ROOT_PASSWORD}
            MYSQL_USER: ${ARTICLES_DB_USER}
            MYSQL_PASSWORD: ${ARTICLES_DB_PASS}
        networks:
            - internal

networks:
    internal:
