version: '3.3'

services:
    news-db:
        image: mysql:8.0
        environment:
            MYSQL_DATABASE: 'news'
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: 'password'
            MYSQL_ROOT_PASSWORD: 'password'
        ports:
            - '3306:3306'
        expose:
            - '3306'
