# We need to use a custom schema.sql to handle custom indexes.
spring:
  jpa:
    hibernate:
      ddl-auto: 'none'
  sql:
    init:
      mode: 'always'

  datasource:
    url: 'jdbc:mysql://localhost:3306/news'
    username: 'user'
    password: 'password'
    driver-class-name: 'com.mysql.cj.jdbc.Driver'
    hikari:
      initialization-fail-timeout: 0

application:
  cross-origin: 'http://localhost:3000'
  auth:
    public-key: ''
    issuer: ''
