FROM node:18-alpine AS runner
WORKDIR /app
ENV NODE_ENV production
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

COPY ./public ./public
COPY --chown=nodejs:nextjs ./.next/standalone ./
COPY --chown=nodejs:nextjs ./.next/static ./.next/static

USER nextjs
ENV PORT 3000
EXPOSE 3000
CMD ["node", "server.js"]
