# Set custom properties:
application:
  cross-origin: 'http://localhost:3000'
  admins:
    - username: 'admin'
      password: '{bcrypt}$2a$10$V.UG.7NEbPzvm0WG1EB9v.pvYOHLd7y6u.oQqPpQw.s4IdaJ4t68q'
  jwt:
    private-key: ''
    public-key: ''
    issuer: ''
